branch-defaults:
  master:
    environment: awscourse
    group_suffix: null
global:
  application_name: awscourse
  branch: null
  default_ec2_keyname: roman_ssh
  default_platform: tomcat-8-java-8
  default_region: eu-west-1
  profile: null
  repository: null
  sc: git